FROM rockylinux:9@sha256:d7be1c094cc5845ee815d4632fe377514ee6ebcf8efaed6892889657e5ddaaa6

RUN dnf -y upgrade --refresh \
    && dnf -y install valkey \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && install -d -o valkey -g valkey -m 0700 /data

COPY docker/valkey-entrypoint.sh /usr/local/bin/valkey-entrypoint

RUN chmod 0555 /usr/local/bin/valkey-entrypoint

USER valkey:valkey
WORKDIR /data

EXPOSE 6379
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/valkey-entrypoint"]
